version: "3.0"

services:

  php:
    image: php
    volumes:
      - ./app:/app
    entrypoint:
      sh /app/start.sh

  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./runtime/mongo:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./runtime/redis:/data